### ISSUE TITLE
LFG start command not being recognised

### ISSUE THREAD

**Issue by meldj08** [AndreTkachenkoOrg/lfg-bot#15]
The bot is not recognising lfg start and is deleting the message as if it wasn't a command

**Comment by dreytko** [comment]
Hello @meldj08.
Did you set up your lfg channel first by using `lfg setup` command? In order to prevent the bot from disrupting other bots and users experience, LFG bot only looks at a specific channel.

**Comment by dreytko** [comment]
I will close the issue for now. If you still have an issue using the bot - consider reopening the issue and mentioning me in the comment.
