### ISSUE TITLE
[IDEA] Add moderation mode configuration

### ISSUE THREAD

**Issue by ohhAtaraxia** [AndreTkachenkoOrg/lfg-bot#24]
Not everyone uses the LFG bot in the looking for group section, when they type in the chat to ask a question their messages get deleted. Therefore there should be an option for the delete function to be switched on and off. The function for omitting (lfg ignore) words from deletion could still be included for the times when the LFG bot is set to always delete non-command messages, but the command would become unnecessary if an on/off command could be added to the delete function of the bot. The bot works great doing what it currently does, but if it didn't have to have the "lfg ignore" function to otherwise speak in chat it would flow well with conversation.

**Comment by dreytko** [comment]
Hello @ohhAtaraxia.
I got your idea and will consider it.
I already have some thoughts about how to implement.
The next week is going to be tough on work and then I will be away on the following week, so maybe it will take a while to try it out.
I will keep you posted and mention you in the next message when I will have more info about it.

**Comment by ohhAtaraxia** [comment]
Sounds good to me! Take your time, just trying to give some constructive
feedback :)

**Comment by dreytko** [comment]
Hello @ohhAtaraxia
I've added the ability to disable/enable moderation mode for an lfg channel.
Please refer to the readme or `lfg help` to get the idea of how to use it.
Feel free to post a comment here if you have any questions.
Have a good day!

**Comment by ohhAtaraxia** [comment]
That's awesome! I will definitely be checking it out 🙂
