### ISSUE TITLE
[IDEA] Add multiple lfg channels support

### ISSUE THREAD

**Issue by Waliers** [AndreTkachenkoOrg/lfg-bot#25]
**Describe the bug**
Running `lfg setup` in multiple channels makes the bot non functioning. It shows the message "this channel is now set up as lfg channel" but it will not delete the messages, Even giving the bot full access rights on the server doesn't fix this.

**To Reproduce**
Steps to reproduce the behaviour:
1. run lfg setup in channel 1
2. run lfg setup in channel 2
3. type a message in channel 2
4. message is not removed

**Expected behaviour**
Running lfg setup should work in all channels and remove all messages in all channels.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Discord App
 - Version: Latest

**Comment by dreytko** [comment]
Hello @Waliers 
Thank you for the explicit explanation of the issue.
The bot was intended to use in one separated channel, where all lfg calls would be located.
I understood your idea. For now, the bot just looks for the first lfg channel, that was created for the channel, and ignores any other. It wasn't just implemented.
I'll change the issue from the bug to the enhancement status, and will consider adding multiple lfg channel support.
I will keep you posted in here in comments.
Thank you for using the bot and providing feedback! Hope you like it!

**Comment by Waliers** [comment]
> 
> 
> Hello @Waliers
> Thank you for the explicit explanation of the issue.
> The bot was intended to use in one separated channel, where all lfg calls would be located.
> I understood your idea. For now, the bot just looks for the first lfg channel, that was created for the channel, and ignores any other. It wasn't just implemented.
> I'll change the issue from the bug to the enhancement status, and will consider adding multiple lfg channel support.
> I will keep you posted in here in comments.
> Thank you for using the bot and providing feedback! Hope you like it!

No worries then and sorry for making it a "bug"! I was thrown off by the message "this channel is now set up as lfg channel" assuming it would work in multiple.

In the first channel it indeed works marvelous (and really good so far as well!) Thanks for the good work and insane fast repsonse!

**Comment by dreytko** [comment]
@Waliers no worries, I have no problem with you creating a bug, just changed the status for myself, to keep track of the things I want to make.
Now, as you closed the issue, I want to ask you - do you need this functionality, or you just thought it should be working that way?
If you are using/would like to have it - then I will think about implementing it.

**Comment by Waliers** [comment]
Hiya, 

It is a "nice to have" feature not really a must have.

To elaborate on this:

We have a discord with both NA and EU members and I thought about having a lfg-eu and a lfg-na channel to seperate it and make it easier for the members. For now I "fixed" it by using your bot in1 lfg-channel with rolecolors for NA people (red) and EU people (blue). 

So if you ever are "bored" and want to add the function it would be nice, but by no means it is a "need this NOW cannot use this" thing xD

I will re-open the feature then and maybe other people can be like, hmm this is something I would like as well :)

**Comment by dreytko** [comment]
Ok, I understood the idea.
I already have an idea from the other users also related to the lfg channel configuration.
So, once I will have time to sit up and try it out, I will try to implement both of them.
As I already said, I will keep you posted in the comments here.
Have a good day!

**Comment by dreytko** [comment]
Hi @Waliers 
I've finally found time to make this feature.
I've tested it and it works well for me.
Should be already working for you as well.

Have a good day!
