### ISSUE TITLE
[IDEA] Change set of questions during event setup

### ISSUE THREAD

**Issue by lSnazzyl** [AndreTkachenkoOrg/lfg-bot#36]
Proposed Bot Improvement:
Currently the bot has a pre-configured "lfg start" command, and I didn't find the questions to be super helpful. Is there a way for you to add something so that I can customize the questions asked in the survey? I understand if you are unable to since I know nothing about coding, but I figured I would make the suggestion.

Thanks

**Comment by dreytko** [comment]
Hello @lSnazzyl 
Thank you for your idea.
I don't think that I'm going to add custom questions support in the near future, as it will increase the load on the server and may affect bot's responsiveness. However, I will consider the possibility and will assess the performance impact of this feature. Thank you.
However, we still can work on the existing survey - if you have any better set of questions, feel free to post them here. Maybe together we will come up to a better set of question.

**Comment by dreytko** [comment]
As there was no response for a month already, I am closing this ticket.
