### ISSUE TITLE
Voice Channel Invite posted along with the LFG message

### ISSUE THREAD

**Issue by ChrisCartagena** [AndreTkachenkoOrg/lfg-bot#53]
It would be a really cool feature if the bot would post a voice channel invite alongside the LFG message if the person looking for the group is currently in a voice channel and requests for the VC to be posted aswell.

**Comment by dreytko** [comment]
Hello @ChrisCartagena 
Thank you for the idea.
My current concern with your idea is that person looking for a group may create an lfg call for a future/uncertain time period (which is 90% of the bot usage I've known), in which case posting an invite link would be pointless or in some cases even cause some issues when people will join VC when they were not expected at that moment.
We can discuss this idea a bit further and might come to an agreement.
Just like a temporary solution - create an invite link to the desired VC and just put it in the description.

**Comment by dreytko** [comment]
Closed due to inactivity.
Consider reopening this ticket in case you want to resume the conversation
