### ISSUE TITLE
Question about moderation command

### ISSUE THREAD

**Issue by MADjo1** [AndreTkachenkoOrg/lfg-bot#60]
hello andre
i was asking you a question about the members and reaction roles before
![image](https://user-images.githubusercontent.com/88328650/141485551-43dd163e-1890-403b-974f-0b3cdf6d670d.png)
this is what where i try to add reactions so people can click them and none are working i cannot add clickable reactions inside or even below (next to the 👍 👎 "here i would like to add custom reactions like 🅰️ 🅱️ that people can click so i see there name" or even in the description would be great but even trying to paste as fastreaction +:a it all results in non clickable images and below everything gets deleted by the bot also the moderate 1 does not let me add anything also a ignore message cannot get reactions.

is there any way you can add this (at end question wanna add custom reactions y or skip so the botom reactions would become to look like below depending on the reacions choosen in unicode ":a,:b,:m" ?
👍 👎 🅰️ 🅱️ Ⓜ️ 

that would realy make my day

**Comment by andretkachenko** [comment]
Hello @MADjo1 
Please try to use `moderate` commands as follows: `lfg moderate 0 <# 732152920539136070>`, but replace `id` of the channel with yours and remove space between `#` and `id`
Then you should be able to add new reactions

**Comment by dreytko** [comment]
Hello @MADjo1 
As far as I can see right now, Discord revokes the bot's ability to moderate reactions, probably due to Discord API upgrade and additional safety measures.
So I was able to add any reaction under any message in lfg channels.
Are you sure that it's LFG bot that manages reactions in your channel?

**Comment by MADjo1** [comment]
Hey Andre, 
This is the chanel



Where i did lfg setup

Now i did  lfg moderate 0 <#daily-runs>

Do i now need to put new lfg start to see result because this did not change anything i cannot add a single reaction to the message in there


reguards Jo

Van: Andrey Tkachenko
Verzonden: vrijdag 12 november 2021 16:35
Aan: AndreTkachenkoOrg/lfg-bot
CC: MADjo1; Mention
Onderwerp: Re: [AndreTkachenkoOrg/lfg-bot] [IDEA] (Issue #60)

Hello @MADjo1
Please try to use moderate commands as follows: lfg moderate 0 <# 732152920539136070>, but replace id of the channel with yours and remove space between # and id
Then you should be able to add new reactions
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dreytko** [comment]
Seems that you're responding to my initial comment, where I provided you a way to mention text channel via id.
First, you're using channel name, not channel id.
Second, you can make it easier by just typing lfg moderate 0 and after add # and start typing your channel's name.

**Comment by MADjo1** [comment]
Hello Andre, 

i now used channel id from developper mode
looks like this

still notting changed


regards Jo

Van: Andrey Tkachenko
Verzonden: vrijdag 12 november 2021 18:57
Aan: AndreTkachenkoOrg/lfg-bot
CC: MADjo1; Mention
Onderwerp: Re: [AndreTkachenkoOrg/lfg-bot] [IDEA] (Issue #60)

Seems that you're responding to my initial comment, where I provided you a way to mention text channel via id.
First, you're using channel name, not channel id.
Second, you can make it easier by just typing lfg moderate 0 and after add # and start typing your channel's name.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dreytko** [comment]
You probably answering me via email,  because it looks like you're posting images, but I can't see any at the site itself

**Comment by MADjo1** [comment]
sorry i did not know and indeed i was answering via mail with images
![image](https://user-images.githubusercontent.com/88328650/141530002-c598f55f-094a-43c8-a0c4-c22b942966af.png)
is the image what i was mailing

and this still did not change anything as for adding reactions
as soon if i add 1 it gets deleted automaticly after 1 or 2 seconds

**Comment by MADjo1** [comment]
but that also did not change anything meaning
i can still not add any reactions or anything

**Comment by dreytko** [comment]
I've just tried to add bot to the different server, and it works as expected to me:
1. Invited bot to the server via the link readme
2. Created new channel `lfg`
3. Used `lfg setup` to setup it
4. Used `lfg moderate 0 #lfg` to disable moderation
5. Send `test` message to ensure moderation no longer applies
6. Created new event via `lfg start` command
7. Tried to add new emotion

Here's the result:
![image](https://user-images.githubusercontent.com/22518570/141531099-0b8570de-7791-4ce5-b0e4-bf2458ce1500.png)

**Comment by MADjo1** [comment]
i will again after running dungeon do the all steps you discribed in your 7 steps
i hope it work for me too

**Comment by MADjo1** [comment]
thanks a bunch Andre, 
there must have been someting wrong with the channel i had
i recreated channel followed the steps and see my result below a GREAT LFG that i am going to promote with friends
the moderation part that is not userfriendly because i think most people dont know how to get a channel ID perhaps make the discription in the help a bit more extended (would be my sugestion)
but that said this is SUPER USER FRIENDLY to maintain
![image](https://user-images.githubusercontent.com/88328650/141600664-52a73045-263c-4ffc-8487-6c2bd18824d1.png)

**Comment by dreytko** [comment]
Glad it now works for you
To be honest, you never really needed channel id to be used with this particular bot, I just confused it with my other's bot command, where there's a command related to the voice channel, which you can't mention, so there's no way to make it work without channel id.
This LFG bot works only with text channels, so it was easier to implement in a user-friendly fashion.
